USE SuperShopDB;
GO

IF OBJECT_ID('dbo.AuditLogs', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.AuditLogs
    (
        AuditLogID INT IDENTITY(1,1) PRIMARY KEY,
        ActionType NVARCHAR(30) NOT NULL,
        TableName NVARCHAR(80) NOT NULL,
        RecordID NVARCHAR(80) NULL,
        [User] NVARCHAR(120) NULL,
        [Timestamp] DATETIME NOT NULL DEFAULT GETDATE(),
        Description NVARCHAR(500) NULL
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_AuditLogs_Timestamp' AND object_id = OBJECT_ID('dbo.AuditLogs'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_AuditLogs_Timestamp ON dbo.AuditLogs ([Timestamp] DESC);
END
GO

-- Seed support checks (safe and duplicate-free)
IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Username='admin')
BEGIN
    INSERT INTO dbo.Users (FullName, Username, Password, Role, Email, SecurityQuestion, SecurityAnswer, CreatedDate)
    VALUES ('System Administrator', 'admin', 'e86f78a8a3caf0b60d8e74e5942aa6d86dc150cd3c03338aef25b7d2d7e3acc7', 'Admin', 'admin@supershop.local', 'What is your favorite color?', '16477688c0e00699c6cfa4497a3612d7e83c532062b64b250fed8908128ed548', GETDATE());
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.Categories WHERE CategoryName='Groceries')
BEGIN
    INSERT INTO dbo.Categories (CategoryName, Description, CreatedDate)
    VALUES ('Groceries', 'Daily essentials', GETDATE());
END
GO

DECLARE @GroceriesID INT;
SELECT TOP 1 @GroceriesID = CategoryID FROM dbo.Categories WHERE CategoryName='Groceries';

IF @GroceriesID IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM dbo.Products WHERE Barcode='890100000099')
BEGIN
    INSERT INTO dbo.Products (ProductName, Barcode, CategoryID, PurchasePrice, SellingPrice, StockQuantity, ReorderLevel, ExpiryDate, SupplierName, Description, CreatedDate)
    VALUES ('Seed Product', '890100000099', @GroceriesID, 100, 130, 25, 5, NULL, 'Seed Supplier', 'Autogenerated sample product', GETDATE());
END
GO

IF OBJECT_ID('dbo.Customers', 'U') IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM dbo.Customers WHERE Phone='01700000000')
BEGIN
    INSERT INTO dbo.Customers (FullName, Phone, Email, Address, LoyaltyPoints, CreatedDate)
    VALUES ('Seed Customer', '01700000000', 'seedcustomer@supershop.local', 'Seed Address', 0, GETDATE());
END
GO
