using System;
using System.Data.SqlClient;
using System.Threading.Tasks;
using Super_Shop_Management_System.Helpers;

namespace Super_Shop_Management_System.BLL
{
    public class SeedDataService
    {
        private readonly DBHelper _dbHelper = new DBHelper();

        public async Task EnsureSeedDataAsync()
        {
            await EnsureAdminAsync();
            await EnsureCategoryAsync();
            await EnsureProductAsync();
            await EnsureCustomerAsync();
        }

        private async Task EnsureAdminAsync()
        {
            const string exists = "SELECT COUNT(1) FROM Users WHERE Username=@Username";
            int count = Convert.ToInt32(await _dbHelper.ExecuteScalarAsync(exists, new SqlParameter("@Username", "admin")));
            if (count > 0) return;

            const string insert = @"INSERT INTO Users (FullName, Username, Password, Role, Email, SecurityQuestion, SecurityAnswer, CreatedDate, PasswordAlgorithm)
                                    VALUES (@FullName, @Username, @Password, @Role, @Email, @SecurityQuestion, @SecurityAnswer, @CreatedDate, @PasswordAlgorithm)";
            await _dbHelper.ExecuteNonQueryAsync(insert,
                new SqlParameter("@FullName", "System Administrator"),
                new SqlParameter("@Username", "admin"),
                new SqlParameter("@Password", SecurityHelper.HashPasswordForStorage("Admin@123")),
                new SqlParameter("@Role", "Admin"),
                new SqlParameter("@Email", "admin@supershop.local"),
                new SqlParameter("@SecurityQuestion", "What is your favorite color?"),
                new SqlParameter("@SecurityAnswer", SecurityHelper.HashValue("blue")),
                new SqlParameter("@CreatedDate", DateTime.Now),
                new SqlParameter("@PasswordAlgorithm", SecurityHelper.CurrentAlgorithm));
        }

        private async Task EnsureCategoryAsync()
        {
            const string exists = "SELECT COUNT(1) FROM Categories WHERE CategoryName=@CategoryName";
            int count = Convert.ToInt32(await _dbHelper.ExecuteScalarAsync(exists, new SqlParameter("@CategoryName", "Groceries")));
            if (count > 0) return;

            const string insert = "INSERT INTO Categories (CategoryName, Description, CreatedDate) VALUES (@CategoryName, @Description, @CreatedDate)";
            await _dbHelper.ExecuteNonQueryAsync(insert,
                new SqlParameter("@CategoryName", "Groceries"),
                new SqlParameter("@Description", "Daily essentials"),
                new SqlParameter("@CreatedDate", DateTime.Now));
        }

        private async Task EnsureProductAsync()
        {
            const string categoryIdQuery = "SELECT TOP 1 CategoryID FROM Categories WHERE CategoryName=@CategoryName";
            object categoryId = await _dbHelper.ExecuteScalarAsync(categoryIdQuery, new SqlParameter("@CategoryName", "Groceries"));
            if (categoryId == null || categoryId == DBNull.Value) return;

            const string exists = "SELECT COUNT(1) FROM Products WHERE Barcode=@Barcode";
            int count = Convert.ToInt32(await _dbHelper.ExecuteScalarAsync(exists, new SqlParameter("@Barcode", "890100000099")));
            if (count > 0) return;

            const string insert = @"INSERT INTO Products (ProductName, Barcode, CategoryID, PurchasePrice, SellingPrice, StockQuantity, ReorderLevel, ExpiryDate, SupplierName, Description, CreatedDate)
                                    VALUES (@ProductName, @Barcode, @CategoryID, @PurchasePrice, @SellingPrice, @StockQuantity, @ReorderLevel, @ExpiryDate, @SupplierName, @Description, @CreatedDate)";
            await _dbHelper.ExecuteNonQueryAsync(insert,
                new SqlParameter("@ProductName", "Seed Product"),
                new SqlParameter("@Barcode", "890100000099"),
                new SqlParameter("@CategoryID", Convert.ToInt32(categoryId)),
                new SqlParameter("@PurchasePrice", 100m),
                new SqlParameter("@SellingPrice", 130m),
                new SqlParameter("@StockQuantity", 25),
                new SqlParameter("@ReorderLevel", 5),
                new SqlParameter("@ExpiryDate", DBNull.Value),
                new SqlParameter("@SupplierName", "Seed Supplier"),
                new SqlParameter("@Description", "Autogenerated sample product"),
                new SqlParameter("@CreatedDate", DateTime.Now));
        }

        private async Task EnsureCustomerAsync()
        {
            const string exists = "SELECT COUNT(1) FROM Customers WHERE Phone=@Phone";
            int count = Convert.ToInt32(await _dbHelper.ExecuteScalarAsync(exists, new SqlParameter("@Phone", "01700000000")));
            if (count > 0) return;

            const string insert = @"INSERT INTO Customers (FullName, Phone, Email, Address, LoyaltyPoints, CreatedDate)
                                    VALUES (@FullName, @Phone, @Email, @Address, @LoyaltyPoints, @CreatedDate)";
            await _dbHelper.ExecuteNonQueryAsync(insert,
                new SqlParameter("@FullName", "Seed Customer"),
                new SqlParameter("@Phone", "01700000000"),
                new SqlParameter("@Email", "seedcustomer@supershop.local"),
                new SqlParameter("@Address", "Seed Address"),
                new SqlParameter("@LoyaltyPoints", 0),
                new SqlParameter("@CreatedDate", DateTime.Now));
        }
    }
}